install.packages("rlang")
install.packages("syuzhet")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("scales")
install.packages("reshape2")
install.packages("dplyr")
library(rlang)
library(syuzhet) #use for sentiment analysis
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
x<- read.csv("Data1.csv",header=TRUE)
str(x)
tweets<-iconv(x$text, from="UTF-8", to="ASCII//TRANSLIT")
str(tweets)
head(tweets)
corpus<-iconv(x$text)
corpus<-Corpus(VectorSource(corpus))
inspect(corpus[1:5])
corpus<-tm_map(corpus,tolower)
inspect(corpus[1:5])
corpus<-tm_map(corpus,removeNumbers)
inspect(corpus[1:5])
corpus<-tm_map(corpus,removeWords,stopwords("english"))
inspect(corpus[1:5])
corpus<-tm_map(corpus,removePunctuation)
inspect(corpus[1:5])
tdm<- TermDocumentMatrix(corpus)
tdm<- as.matrix(tdm)
tdm[1:10,1:20]
print(tdm)
a<-rowSums(tdm)
a<-subset(a,a>=45)
barplot(a,col=rainbow(50))
